### ISSUE TITLE
anime 图像的生成效果较差，与参考图不一致

### ISSUE THREAD

**Issue by JoshonSmith** [MS-Diffusion/MS-Diffusion#3]
请问MS-Diffusion在漫画卡通类数据上训练过吗？
我发现这类数据上的效果较差，尤其是多主体生成时，与参考图很不一致
参考图：
<img width="501" alt="exp_boy2" src="https://github.com/MS-Diffusion/MS-Diffusion/assets/69639577/02f79b0f-c592-42f5-bf66-23d421f0d599">

结果图：
![4](https://github.com/MS-Diffusion/MS-Diffusion/assets/69639577/91b447c9-cb86-4974-98f7-39a9bd53341d)

**Comment by sherrydoge** [comment]
我们的训练数据几乎不包含卡通图像，但你展示的例子还是有点不符合预期。方便提供一下你输入的其他参数吗，比如prompt box和scale等

**Comment by JoshonSmith** [comment]
提示词：a **boy** is playing with a **dog** in the forest
boxes = [[[0., 0., 0., 0.], [0., 0., 0., 0.]]]
scale=0.6
dog的参考图是
![exp_dog](https://github.com/MS-Diffusion/MS-Diffusion/assets/69639577/10d2e320-d594-42d5-8c98-b008b9dd6056)

**Comment by sherrydoge** [comment]
在没有启用auto layout guidance的情况下，box不能设置成全零，会导致参考图无法作用到生成过程。这个例子推荐用左右box如`boxes = [[[0., 0.25, 0.4, 0.75], [0.6, 0.25, 1., 0.75]]]`

**Comment by JoshonSmith** [comment]
> 我们的训练数据几乎不包含卡通图像，但你展示的例子还是有点不符合预期。方便提供一下你输入的其他参数吗，比如prompt box和scale等

请问training code有开源计划吗，用于训练卡通图像

**Comment by sherrydoge** [comment]
training code后续会开源，可能需要等待一些时间，感谢理解！
