### ISSUE TITLE
Can it be used with sd1.5 series?

### ISSUE THREAD

**Issue by blx0102** [MS-Diffusion/MS-Diffusion#4]
Thanks

**Comment by sherrydoge** [comment]
For now, there is only a checkpoint for SDXL-base-1.0. Since we keep the base model freezing, MS-Diffusion can also support SD1.5 with proper training.

**Comment by blx0102** [comment]
Thanks for your reply, do you have any plans for official training on SD1.5?

**Comment by blx0102** [comment]
Alright, thank you.
