### ISSUE TITLE
Is there a way to achieve the effect of wearing clothes through this algorithm, such as uploading a full body picture and clothes, which can automatically switch to the character's body

### ISSUE THREAD

**Issue by libai-lab** [MS-Diffusion/MS-Diffusion#6]
Is there a way to achieve the effect of wearing clothes through this algorithm, such as uploading a full body picture and clothes, which can automatically switch to the character's body

**Comment by sherrydoge** [comment]
We have not developed this feature, but you can try our model with inpainting ControlNet. It should be noted that MS-Diffusion is a personalized model where the subject is injected as a concept, which means the details would be worse than SOTA try-on methods.
