### ISSUE TITLE
Training code and parameter initialize

### ISSUE THREAD

**Issue by jianzongwu** [MS-Diffusion/MS-Diffusion#8]
Hi, can you tell me about your plan to release the training code?

By the way, I wonder if your model was initialized from an IP-Adapter or similar models. Or you just initialize from Stable-Diffusion-XL? I didn't find the answer in the paper.

**Comment by sherrydoge** [comment]
The plan to release the training code is still under assessment.
The model is initialized from SDXL. The Grounding Resampler is initialized randomly and the image cross attentions are initialized from the text cross attentions.
Thanks for your interest and patience!

**Comment by jianzongwu** [comment]
Thank you very much.

Feel free to cloes this issue
